### ISSUE TITLE
Can I test on my own dataset?

### ISSUE THREAD

**Issue by Ssakura-go** [YC-Liang/DRT#1]
Dear author,

I'm glad to meet with your work, which combines attention, recursive structure, and skip-connection (DRT). I think such a method is what my task needs. Therefore, I want to test your pre-trained model on my test dataset and get a conclusion whether my guess is correct. It's difficult for me to find an entrance.

If you are free, please give me a hand. 
Thks~

**Comment by YC-Liang** [comment]
Hi,

I am glad you find the work useful. The pre-trained models are stored in the checkpoint folder. The swin-transformer block is implemented in the transformer_block.py whereas the main model is implemented in the DRT jupyter notebook. If you just want to load our model and test it somewhere else, you can do so by copying the code in the "Model Desgin" section of the notebook to your editor. Of course, don't foget to have the right imports and also have the transformer_block.py and models downloaded. Hope this helps.

Thanks
