### ISSUE TITLE
Can the input hight and width be the different?

### ISSUE THREAD

**Issue by missu123** [YC-Liang/DRT#2]
In the code, Input hight and width should be the same, but i want to set them to different value, where I need to change?

**Comment by YC-Liang** [comment]
Hi, the transformer network itself can only process square images. At training stage, the data loader uses the 'training_image_size' to randomly crop a square portion of a training image (can be in any size) to generate trainning data. At testing stage, image of any size is firstly padded to a square dimenion for the network to process, and then the extra dimensions are cropped away from the output to display the original derained image. Thanks.
