### ISSUE TITLE
The link of Rain100H datasets and Rain100L datasets may be invalid

### ISSUE THREAD

**Issue by wonlp** [YC-Liang/DRT#3]
Thanks for your contribution, which gives me much inspiration.  I found that the link of two datasets are invalid. If you could share a new link with me, I would appreciate it.

**Comment by YC-Liang** [comment]
Hi, the dataset should be available from the Baidu cloud drive, [Link Here](https://pan.baidu.com/s/1SR7yULy0VZ_JZ4Vawqs7gg#list/path=%2F)

Sorry unfortunately my system has changed and I do not have the data with me locally to upload.
In the case that you cannot access Baidu cloud, could you try to contact the author who publishes the data set?

**Comment by wonlp** [comment]
谢谢您的热心帮助。
我还想请教您，您的模型在rain800初始化后，在rain100h和rain100l上训练时，是将rain100h和rain100l合在一起训练的？还是先在其中一个上面训练，然后再在另一个上面训练呢？




| |
王利萍
南京邮电大学
19852867689
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 02/21/2023 06:29 |
| To | ***@***.***> |
| Cc | Wang ***@***.***>***@***.***> |
| Subject | Re: [YC-Liang/DRT] The link of Rain100H datasets and Rain100L datasets may be invalid (Issue #3) |

Hi, the dataset should be available from the Baidu cloud drive, Link Here

Sorry unfortunately my system has changed and I do not have the data with me locally to upload.
In the case that you cannot access Baidu cloud, could you try to contact the author who publishes the data set?

**Comment by YC-Liang** [comment]
没有合在一起，是分开的。

**Comment by wonlp** [comment]
好的，明白了，谢谢😊



| |
王利萍
南京邮电大学
19852867689
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月21日 14:54 |
| 收件人 | ***@***.***> |
| 抄送至 | Wang ***@***.***>***@***.***> |
| 主题 | Re: [YC-Liang/DRT] The link of Rain100H datasets and Rain100L datasets may be invalid (Issue #3) |

没有合在一起，是分开的。
