### ISSUE TITLE
a question about params 

### ISSUE THREAD

**Issue by wonlp** [YC-Liang/DRT#4]
I find that the params of DRT is about 2.53M but not 1.18M when I directly run the script train.py. Could you tell what's wrong with it?

**Comment by YC-Liang** [comment]
Hi, my best guess is that the packge `torch-summary` has gone through significant changes over last year and the way they calculate everything might be slightly different. You can potentially try to downgrade the version to 0.8.2 to try again. 

With that said, can you also double check whether the parameters, especially STB number and RTB numbers are the same as the paper?

**Comment by wonlp** [comment]
thanks you again.I think the bug may be related to the recursive layer. torchsummary can't calculate accurately when the model has recursive layer. I try another method to calculate, it's params exactly is 1.18M.



| |
王利萍
南京邮电大学
19852867689
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 04/03/2023 09:00 |
| To | ***@***.***> |
| Cc | Wang ***@***.***>***@***.***> |
| Subject | Re: [YC-Liang/DRT] a question about params (Issue #4) |

Hi, my best guess is that the packge torch-summary has gone through significant changes over last year and the way they calculate everything might be slightly different. You can potentially try to downgrade the version to 0.8.2 to try again.

With that said, can you also double check whether the parameters, especially STB number and RTB numbers are the same as the paper?
