### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Bayonetta1** [YC-Liang/DRT#5]
从哪里可以得到Rain800数据集

**Comment by YC-Liang** [comment]
你好，这是rain800原作者提供的链接，
https://drive.google.com/file/d/1cMXWICiblTsRl1zjN8FizF5hXOpVOJz4/view
如果以上链接不可用可以尝试联系原作者，
https://github.com/hezhangsprinter/DID-MDN
谢谢

**Comment by Bayonetta1** [comment]
所以Rain800是从DID的数据集抽取的图片吗，感谢您的回答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YC-Liang/DRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月15日(星期一) 上午8:59
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [YC-Liang/DRT] Dataset (Issue #5)





 
你好，这是rain800原作者提供的链接，
 https://drive.google.com/file/d/1cMXWICiblTsRl1zjN8FizF5hXOpVOJz4/view
 如果以上链接不可用可以尝试联系原作者，
 https://github.com/hezhangsprinter/DID-MDN
 谢谢

**Comment by YC-Liang** [comment]
你好，更正下，rain800是公布在这个github里，
https://github.com/hezhangsprinter/ID-CGAN
谢谢

**Comment by YC-Liang** [comment]
README已更新

**Comment by Bayonetta1** [comment]
感谢您的回答，但是https://github.com/hezhangsprinter/ID-CGAN中的Rain800下载链接已经失效，我用该作者的DID数据集进行训练，DID数据集是512x1024的图片但是左边是有雨右边是无雨，我也更改了dataloader中的顺序，可是训练到70轮后会出现梯度爆炸的问题，是因为数据集的问题吗

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YC-Liang/DRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月16日(星期二) 上午8:27
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [YC-Liang/DRT] Dataset (Issue #5)





 
你好，更正下，rain800是公布在这个github里，
 https://github.com/hezhangsprinter/ID-CGAN
 谢谢
