### ISSUE TITLE
gradient explosion

### ISSUE THREAD

**Issue by Bayonetta1** [YC-Liang/DRT#7]
为什么试了两个数据集都出现了梯度爆炸的问题，难道是有参数设置的不对吗，能否请教一下，感谢！

**Comment by YC-Liang** [comment]
如果用的数据集里的单张图片是有雨和没雨的话，一开始需要写下代码把有雨和无雨的分开。有雨的用来做input，无雨的是用来算loss。我没记错的话，我的训练过程里是将图片随机切成96x96的方格，然后用这个方格来训练。如果将包含有雨和无雨的图片一起给的话，input可能有雨或者无雨，算loss的参考图片也是。自然训练会出错。

**Comment by Bayonetta1** [comment]
感谢您的回复，不是有三个训练的目录吗Rain-800这个数据集是输入和标签在一起的，我没有这个数据集所以用了Rain800作者的另一个数据集，也是一张图片包含输入和标签，但是和Rain800是反过来的，在dataloader里面我也改了，然后用这个数据集从头开始训练，到80 90轮就会发生梯度爆炸，然后最佳损失大概在0.5-0.6左右，然后我又Rain100这个数据集，在刚刚训练的这个checkpoint上准备拿Rain100再次训练，但是跑了10轮左右又梯度爆炸了，这是什么原因呢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YC-Liang/DRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 晚上7:21
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [YC-Liang/DRT] gradient explosion (Issue #7)





 
如果用的数据集里的单张图片是有雨和没雨的话，一开始需要写下代码把有雨和无雨的分开。有雨的用来做input，无雨的是用来算loss。我没记错的话，我的训练过程里是将图片随机切成96x96的方格，然后用这个方格来训练。如果将包含有雨和无雨的图片一起给的话，input可能有雨或者无雨，算loss的参考图片也是。自然训练会出错。

**Comment by Bayonetta1** [comment]
Rain100是有雨和无雨分开的文件夹可是还会梯度爆炸

**Comment by RussLoveHitIron** [comment]
你好，请问你解决了这个问题吗

**Comment by Bayonetta1** [comment]
感谢你的回复，我调大batchsize之后就解决了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YC-Liang/DRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月21日(星期天) 晚上11:04
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [YC-Liang/DRT] gradient explosion (Issue #7)





 
你好，请问你解决了这个问题吗
