### ISSUE TITLE
loss explosion

### ISSUE THREAD

**Issue by zkawfanx** [YC-Liang/DRT#8]
Hi, there. I tried to train your model on my own dataset following the default setting but found that the loss decreases gradually before about 80 epochs while suddenly exploded to thousands. Many tries meet the same problem and the same on the rain13k dataset. Do you have any ideas of this issue or ever met with such problem when you trained your model for the final 4600 epochs?

Thank you.

**Comment by YC-Liang** [comment]
Hi, sorry for the delay, as reported by others, the issues should be solved if you change to a larger batch size. Thanks!
